baseURL = 'https://mangr3n.github.io/'
languageCode = 'en-us'
title = 'David Boyer'
theme = "PaperMod"

[params]
  homeInfoParams = { Title = "Hello!", Content = "This is my personal site." }
  ShowReadingTime = true